DROP TABLE IF EXISTS REFERENCE_AIRCON_TIMER_STATE
GO

CREATE TABLE REFERENCE_AIRCON_TIMER_STATE(
    StateId INT NOT NULL
  , Value NVARCHAR(255) NOT NULL
  , PRIMARY KEY(StateId)
)
GO

INSERT INTO REFERENCE_AIRCON_TIMER_STATE(StateId, Value)
VALUES(0, 'off')
  , (1, 'on')
GO
