DROP TABLE IF EXISTS REFERENCE_AIRCON_TEMPERATURE
GO

CREATE TABLE REFERENCE_AIRCON_TEMPERATURE(
    StateId INT NOT NULL
  , Value NVARCHAR(255) NOT NULL
  , PRIMARY KEY(StateId)
)
GO

INSERT INTO REFERENCE_AIRCON_TEMPERATURE(StateId, Value)
VALUES(24, 'TODO insert byte code for 24 degrees here')
  , (28, 'TODO insert byte code for 28 degrees here')
GO
