DROP TABLE IF EXISTS REFERENCE_AIRCON_MODE
GO

CREATE TABLE REFERENCE_AIRCON_MODE(
    StateId INT NOT NULL
  , Value NVARCHAR(255) NOT NULL
  , PRIMARY KEY(StateId)
)
GO

INSERT INTO REFERENCE_AIRCON_MODE(StateId, Value)
VALUES(1, 'aircon')
  , (2, 'dehumidifier')
  , (3, 'heater')
GO
