DROP TABLE IF EXISTS STATUS_LIGHTING
GO

CREATE TABLE STATUS_LIGHTING(
    Mode INT NOT NULL
  , FOREIGN KEY(Mode) REFERENCES REFERENCE_LIGHTING(StateId)
)
GO

INSERT INTO STATUS_LIGHTING(Mode)
VALUES(2)
GO
